version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: run.py
      FLASK_ENV: production
      DATABASE_URL: "mysql+pymysql://root:Commando1+@db/EpicShi_Event_Management"
    restart: always
    command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app  # Use Gunicorn config
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents node_modules issues inside container

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Commando1+
      MYSQL_DATABASE: EpicShi_Event_Management
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql  # Ensures database persistence

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  mysql_data:  # Persistent volume for MySQL
